name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'assets/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'assets/**'

  workflow_dispatch:

jobs:
  run-jvm-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: create dummy keystore.properties
        run: echo 'storeFile=dummy.jks' > keystore.properties

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: run tests
        run: ./gradlew test --stacktrace
